### ISSUE TITLE
QT Test: Issue with duplication on "Open, future and Past " tests

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#430] opened 2020-09-15 08:22 UTC
**Describe the bug**
I have submitted two tests today for the dry run and when I check my account - whilst they are not active the tests are duplicated in the open and past tests.  It also auto submitted the situational judgement test and it is still showing in the Open tests although it is now submitted.  

**Expected behavior**
I would expect to see both tests in the "past" tab and to only be listed once.  I would expect this behaviour for auto-submitted and manually submitted tests. 

**Screenshots**
Open screen
![Screenshot 2020-09-15 at 09.17.59.png](https://images.zenhubusercontent.com/5e3c2b35e9bf7c0ea1c2859a/e64f71a4-5740-47ee-8abd-486e10c50195)

Closed screen![Screenshot 2020-09-15 at 09.18.06.png](https://images.zenhubusercontent.com/5e3c2b35e9bf7c0ea1c2859a/996350d2-426e-45af-8e70-76a24519586d)

**Comment by warrensearle** [comment] 2020-09-15 09:41
This is a duplicate of #431 which has been fixed

**Closed** 2020-09-15 15:54 UTC
Labels: bug
